project:
  name: start

spring:
  messages:
    basename: i18n/messages/home
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giraffe
    username: root
    password: root

  thymeleaf:
    cache: false #重点是这个要设置false不然会无效
#    　　prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
#mybatis-plus
mybatis-plus:
  ## 这个可以不用配置，因其默认就是这个路径
  mapper-locations: classpath:/mybatis/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.holmium.springboot.repository.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.giraffe.tree.sys.entity
logging:
  level:
    cn.zhxu.bs: DEBUG
bean-searcher:
  packages: com.giraffe.tree.customer